object Versions {
    const val Compose = "1.5.2"
    const val ComposeLib = "1.5.0"
    const val Hilt = "2.47"
    const val HiltNavigationCompose = "1.0.0"
    const val CoreKtx = "1.10.1"
    const val AppCompat = "1.6.1"

    const val Material = "1.10.0-alpha06"
    const val Lifecycle = "2.6.1"
    const val ActivityCompose = "1.7.2"
    const val Junit = "4.13.2"
    const val AndroidxJunit = "1.1.2"
    const val Espresso = "3.3.0"
    const val NavigationCompose = "2.7.1"
    const val Accompanist = "0.32.0"

    const val Ktor = "1.6.0"
    const val KotlinxSerialization = "1.2.1"
    const val Okhttp = "4.7.2"
    const val GitVersion = "0.4.13"
    const val ObjectBox = "3.7.0"

    const val Timber = "5.0.1"
    const val Kotlin = "1.9.0"
    const val AGT = "7.1.3"
    const val ComposePaging = "3.2.0"
    const val LottieCompose = "6.1.0"
    const val ConstraintLayoutCompose = "1.0.1"
    const val KotlinxDatetime = "0.4.0"
    const val Coil = "2.4.0"
}
