name: 🚀 Build Apk     .

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Cache
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.0.0
        with:
          configuration: "config/configuration.json"
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # create keystore.jks
      - name: Create keystore.jks
        run: |
          echo $KEY_STORE > app/key.out
          base64 -di app/key.out > app/keystore.jks
        env:
          KEY_STORE: ${{ secrets.KEY_STORE }}

      # create plaKeystore.jks
      - name: Create plaKeystore.jks
        run: |
          echo $PLAYKEY_STORE > app/playKey.out
          base64 -di app/playKey.out > app/plaKeystore.jks
        env:
          KEY_STORE: ${{ secrets.PLAYKEY_STORE }}

      # create key.properties
      - name: Create key.properties
        run: |
          echo $KEY_PROPERTIES > out.properties
          base64 -di out.properties > key.properties
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      # create playKey.properties
      - name: Create playKey.properties
        run: |
          echo $PLAYKEY_PROPERTIES > playOut.properties
          base64 -di playOut.properties > playKey.properties
        env:
          KEY_PROPERTIES: ${{ secrets.PLAYKEY_PROPERTIES }}

      # create serviceAccountJson
      - name: Create serviceAccountJson
        run: |
          echo $SERVICE > services_account.out
          base64 -di services_account.out > app/services_account.json
        env:
          NATIVE_CPP: ${{ secrets.SERVICE }}

      # create native-lib.cpp
      - name: Create native-lib.cpp
        run: |
          echo $NATIVE_CPP > app/src/main/cpp/native-lib.out
          base64 -di app/src/main/cpp/native-lib.out > app/src/main/cpp/native-lib.cpp
        env:
          NATIVE_CPP: ${{ secrets.NATIVE_CPP }}

      - name: Build Apk
        run: bash ./gradlew :app:assembleRelease

      - name: upload apk
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "${{steps.github_release.outputs.changelog}}"
          files: |
            app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Playstore AppData
        run: ./gradlew bootstrapListing

      - name: Upload Bubnle to Playconsole
        run: ./gradlew app:publishGooglePlayBundle
