name: 🚀 Build Apk     .

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Cache
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.0.0
        with:
          configuration: "config/configuration.json"
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # create google-service.json
#      - name: Create google-service.json
#        run: echo $GOOGLE_SERVICES > app/google-services.json
#        env:
#          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}

      # create keystore.jks
      - name: Create keystore.jks
        run: |
          echo $KEY_STORE > app/key.out
          base64 -di app/key.out > app/keystore.jks
        env:
          KEY_STORE: ${{ secrets.KEY_STORE }}

      # create key.properties
      - name: Create key.properties
        run: |
          echo $KEY_PROPERTIES > out.properties
          base64 -di out.properties > key.properties
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      # create native-lib.cpp
      - name: Create native-lib.cpp
        run: |
          echo $NATIVE_CPP > app/src/main/cpp/native-lib.out
          base64 -di app/src/main/cpp/native-lib.out > app/src/main/cpp/native-lib.cpp
        env:
          NATIVE_CPP: ${{ secrets.NATIVE_CPP }}

      - name: Build Apk
        run: bash ./gradlew :app:assembleRelease
        env:
          KEY_STORE: ${{ secrets.KEY_STORE }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: Build App Bundle
        run: bash ./gradlew :app:bundleRelease
        env:
          KEY_STORE: ${{ secrets.KEY_STORE }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: Upload Resource
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "${{steps.github_release.outputs.changelog}}"
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}